In [ ]:
# 首先比较一下数据集并没有交集
import pandas as pd
data_origin = pd.read_excel('Original_Data/20240627Mg_alloy.xlsx',sheet_name = 'Sheet1',header = 0)
print(data_origin.columns)
display(data_origin)

# 选出模型所使用的基础特征作为原始数据
data_train = data_origin[['No.','合金成分（wt.%）',  'Grain Size','Precipitate Distribution', 'Habit Plane', '屈服强度','抗拉强度 (UTS)',]]
display(data_train)

# 需要判断这里的数据和验证集的数据有没有重复的
data_validation = pd.read_excel('Original_Data/20240127Validation.xlsx',header = 0)
ls = ['屈服强度','抗拉强度 (UTS)']
df1 = data_validation[ls]
df2 = data_train[ls]
common_rows = pd.merge(df1, df2, on=ls, how='inner')

# 检查是否有重复的行
if not common_rows.empty:
    print("存在重复的数据:")
    print(common_rows)
else:
    print("没有重复的数据。")
    print("经验证，并不为同一个材料")

Index(['Unnamed: 0', '原数据编号', 'No.', '合金成分（wt.%）', '屈服强度', '抗拉强度 (UTS)',
       'Grain Size', '惯习面名称', '第二相体积比', '形貌（球形，片层，杆状）',
       'Precipitate Distribution', 'Habit Plane', '直径', '长度', '宽度', '纵横比',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20', 'Unnamed: 21'],
      dtype='object')

,Unnamed: 0,原数据编号,No.,合金成分（wt.%）,屈服强度,抗拉强度 (UTS),Grain Size,惯习面名称,第二相体积比,形貌（球形，片层，杆状）,...,直径,长度,宽度,纵横比,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,231106数据编号,1,1,Mg-0.6946Y-0.0299Fe-0.0562Si,72,174,20.96,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造+固溶+挤压,500°C/12h+400°C，25:1,NaN,NaN,https://doi.org/10.1016/j.jmrt.2023.08.166
1,NaN,2,2,Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si,84,188,18.37,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造+固溶+挤压,500°C/12h+400°C，25:1,NaN,NaN,https://doi.org/10.1016/j.jmrt.2023.08.166
2,NaN,3,3,Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si,86,188,13.22,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造+固溶+挤压,500°C/12h+400°C，25:1,NaN,NaN,https://doi.org/10.1016/j.jmrt.2023.08.166
3,NaN,4,4,Mg-2.54Gd-0.51Zn-0.3Mn,284,362,160.00,LPSO,5,片层,...,NaN,NaN,NaN,NaN,NaN,铸造+固溶+挤压,515°C/16h+320°C，6.25:1,NaN,NaN,https://doi.org/10.1016/j.jallcom.2023.171804
4,NaN,5,5,Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn,316,382,175.00,LPSO,7,片层,...,NaN,NaN,NaN,NaN,NaN,铸造+固溶+挤压,515°C/16h+320°C，6.25:1,NaN,NaN,https://doi.org/10.1016/j.jallcom.2023.171804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,NaN,476,876,Mg-9Al-3Sn-0.3Mn,140,157,58.00,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造,NaN,NaN,NaN,Mg-Al-Sn-Mn系镁合金显微组织与力学性能的研究 - 中国知网 (cnki.net)
876,NaN,477,877,Mg-1Al-5Sn-0.3Mn,68,161,753.00,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造,NaN,NaN,NaN,Mg-Al-Sn-Mn系镁合金显微组织与力学性能的研究 - 中国知网 (cnki.net)
877,NaN,478,878,Mg-1Al-5Sn-0.3Mn,85,190,357.00,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造,NaN,NaN,NaN,Mg-Al-Sn-Mn系镁合金显微组织与力学性能的研究 - 中国知网 (cnki.net)
878,NaN,479,879,Mg-1Al-5Sn-0.3Mn,121,180,60.00,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造,NaN,NaN,NaN,Mg-Al-Sn-Mn系镁合金显微组织与力学性能的研究 - 中国知网 (cnki.net)
879,NaN,480,880,Mg-1Al-5Sn-0.3Mn,156,184,56.00,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,铸造,NaN,NaN,NaN,Mg-Al-Sn-Mn系镁合金显微组织与力学性能的研究 - 中国知网 (cnki.net)

,No.,合金成分（wt.%）,Grain Size,Precipitate Distribution,Habit Plane,屈服强度,抗拉强度 (UTS)
0,1,Mg-0.6946Y-0.0299Fe-0.0562Si,20.96,0,0,72,174
1,2,Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si,18.37,0,0,84,188
2,3,Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si,13.22,0,0,86,188
3,4,Mg-2.54Gd-0.51Zn-0.3Mn,160.00,晶界+晶内,基面,284,362
4,5,Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn,175.00,晶界+晶内,基面,316,382
...,...,...,...,...,...,...,...
875,876,Mg-9Al-3Sn-0.3Mn,58.00,晶界+晶内,1,140,157
876,877,Mg-1Al-5Sn-0.3Mn,753.00,晶界+晶内,1,68,161
877,878,Mg-1Al-5Sn-0.3Mn,357.00,晶界+晶内,1,85,190
878,879,Mg-1Al-5Sn-0.3Mn,60.00,晶界+晶内,1,121,180
879,880,Mg-1Al-5Sn-0.3Mn,56.00,晶界+晶内,1,156,184

存在重复的数据:
    屈服强度 抗拉强度 (UTS)
0  130.0      265.0

In [2]:
import pymatgen
import torch

In [37]:
# 删除抗拉强度不正常的
ls = ['屈服强度','抗拉强度 (UTS)']

# 删除屈服强度或者抗拉强度为0的行或者列
# method 1 : 使用drop，直接修改原本的dataframe
zero_num=len(data_train[data_train['屈服强度']==0].index)
if zero_num == 0:
    print('没有为0的屈服强度')
else:
    print(f'有{zero_num}个为0的副本')
data_train.drop(data_train[data_train['屈服强度']==0].index,inplace = True)
display(data_train)

# 需要去掉晶粒尺寸400以上的数据
print(data_train['Grain Size'].nlargest(10))

drop_num= len(data_train[data_train['Grain Size']>=400])

data_train.drop(data_train[data_train['Grain Size']>=400].index, inplace = True)
print(f'晶粒尺寸提出{drop_num}个样本后的结果：')
print(data_train['Grain Size'].nlargest(10))
display(data_train)

# 需要去掉两个特别的晶粒值
data_train.drop(data_train[data_train['Precipitate Distribution']=='晶粒'].index,inplace = True)
# 验证数据集是否有重合

没有为0的屈服强度

C:\Users\acer-pc\AppData\Local\Temp\ipykernel_8848\238355804.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.drop(data_train[data_train['屈服强度']==0].index,inplace = True)

,No.,合金成分（wt.%）,Grain Size,Precipitate Distribution,Habit Plane,屈服强度,抗拉强度 (UTS),Al,Zn,Mn,...,Sr,Sm,Sc,Gd,Y,Zr,Nd,Ag,Yb,追踪编号
0,1,Mg-0.6946Y-0.0299Fe-0.0562Si,20.96,0,0,72,174,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0000,0.6946,0.0,0.0,0.0,0.0,No1-Mg-0.6946Y-0.0299Fe-0.0562Si
1,2,Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si,18.37,0,0,84,188,0.0,0.00,0.0,...,0.0,0.0,0.0,0.2714,0.7323,0.0,0.0,0.0,0.0,No2-Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si
2,3,Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si,13.22,0,0,86,188,0.0,0.00,0.0,...,0.0,0.0,0.0,0.7524,0.6239,0.0,0.0,0.0,0.0,No3-Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si
3,4,Mg-2.54Gd-0.51Zn-0.3Mn,160.00,晶界+晶内,基面,284,362,0.0,0.51,0.3,...,0.0,0.0,0.0,2.5400,0.0000,0.0,0.0,0.0,0.0,No4-Mg-2.54Gd-0.51Zn-0.3Mn
4,5,Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn,175.00,晶界+晶内,基面,316,382,0.0,0.46,0.3,...,0.0,0.0,0.0,1.7900,0.6800,0.0,0.0,0.0,0.0,No5-Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,Mg-6Al-3Sn-0.3Mn,60.00,晶界+晶内,1,116,204,6.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No867-Mg-6Al-3Sn-0.3Mn
875,876,Mg-9Al-3Sn-0.3Mn,58.00,晶界+晶内,1,140,157,9.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No868-Mg-9Al-3Sn-0.3Mn
877,878,Mg-1Al-5Sn-0.3Mn,357.00,晶界+晶内,1,85,190,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No869-Mg-1Al-5Sn-0.3Mn
878,879,Mg-1Al-5Sn-0.3Mn,60.00,晶界+晶内,1,121,180,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No870-Mg-1Al-5Sn-0.3Mn-2
879,880,Mg-1Al-5Sn-0.3Mn,56.00,晶界+晶内,1,156,184,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No871-Mg-1Al-5Sn-0.3Mn-3

763    396.0
354    376.0
704    375.0
395    374.0
877    357.0
703    350.0
768    334.0
816    331.0
769    330.0
764    324.0
Name: Grain Size, dtype: float64
晶粒尺寸提出0个样本后的结果：
763    396.0
354    376.0
704    375.0
395    374.0
877    357.0
703    350.0
768    334.0
816    331.0
769    330.0
764    324.0
Name: Grain Size, dtype: float64

C:\Users\acer-pc\AppData\Local\Temp\ipykernel_8848\238355804.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.drop(data_train[data_train['Grain Size']>=400].index, inplace = True)

,No.,合金成分（wt.%）,Grain Size,Precipitate Distribution,Habit Plane,屈服强度,抗拉强度 (UTS),Al,Zn,Mn,...,Sr,Sm,Sc,Gd,Y,Zr,Nd,Ag,Yb,追踪编号
0,1,Mg-0.6946Y-0.0299Fe-0.0562Si,20.96,0,0,72,174,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0000,0.6946,0.0,0.0,0.0,0.0,No1-Mg-0.6946Y-0.0299Fe-0.0562Si
1,2,Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si,18.37,0,0,84,188,0.0,0.00,0.0,...,0.0,0.0,0.0,0.2714,0.7323,0.0,0.0,0.0,0.0,No2-Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si
2,3,Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si,13.22,0,0,86,188,0.0,0.00,0.0,...,0.0,0.0,0.0,0.7524,0.6239,0.0,0.0,0.0,0.0,No3-Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si
3,4,Mg-2.54Gd-0.51Zn-0.3Mn,160.00,晶界+晶内,基面,284,362,0.0,0.51,0.3,...,0.0,0.0,0.0,2.5400,0.0000,0.0,0.0,0.0,0.0,No4-Mg-2.54Gd-0.51Zn-0.3Mn
4,5,Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn,175.00,晶界+晶内,基面,316,382,0.0,0.46,0.3,...,0.0,0.0,0.0,1.7900,0.6800,0.0,0.0,0.0,0.0,No5-Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,Mg-6Al-3Sn-0.3Mn,60.00,晶界+晶内,1,116,204,6.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No867-Mg-6Al-3Sn-0.3Mn
875,876,Mg-9Al-3Sn-0.3Mn,58.00,晶界+晶内,1,140,157,9.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No868-Mg-9Al-3Sn-0.3Mn
877,878,Mg-1Al-5Sn-0.3Mn,357.00,晶界+晶内,1,85,190,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No869-Mg-1Al-5Sn-0.3Mn
878,879,Mg-1Al-5Sn-0.3Mn,60.00,晶界+晶内,1,121,180,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No870-Mg-1Al-5Sn-0.3Mn-2
879,880,Mg-1Al-5Sn-0.3Mn,56.00,晶界+晶内,1,156,184,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No871-Mg-1Al-5Sn-0.3Mn-3

C:\Users\acer-pc\AppData\Local\Temp\ipykernel_8848\238355804.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_train.drop(data_train[data_train['Precipitate Distribution']=='晶粒'].index,inplace = True)

In [38]:
# 开始改变合金成分
import re

df = data_train
# List of elements to include as columns
elements = ['Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn', 'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni',
            'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc', 'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb']

for element in elements:
       df[element] = 0.0


def extract_elements(compound):
       # Extract element and percentage pairs using regular expression
       matches = re.findall(r'(\d+\.?\d*)\s*([A-Za-z]+)', compound)
       element_dict = {elem: float(pct) for pct,elem in matches}
       return element_dict


# Apply extraction to each row
for i, row in df.iterrows():
       compound = re.sub(r'\s*\([^)]*\)', '', row['合金成分（wt.%）'])
       element_dict = extract_elements(compound)

       # Update the DataFrame with the extracted values
       for element, percentage in element_dict.items():
              if element in elements:
                     df.at[i, element] = percentage

       # Calculate the Mg percentage
       total_other_elements = sum(element_dict.values())
       # 第i行的'Mg'元素含量计算
       df.at[i, 'Mg'] = 100.0 - total_other_elements


# 为每个材料设置基本的序号

df['追踪编号'] =  df['合金成分（wt.%）']

# 使用字典来跟踪每个成分名的出现次数
composition_count = {}
no_counter = 1  # 初始化No列的数字

for index, row in df.iterrows():
    compound = row['合金成分（wt.%）']
    # 如果内容在成分字典中，说明编号需要加1，同时赋值这个编号给材料
    if compound in composition_count:
        composition_count[compound] += 1
        df.at[index, '追踪编号'] += '-' + str(composition_count[compound])
    else:
        composition_count[compound] = 1
    # 在追踪编号开头添加No列的数字
    df.at[index, '追踪编号'] = 'No' + str(no_counter) + '-' + df.at[index, '追踪编号']
    no_counter += 1

display(df)

C:\Users\acer-pc\AppData\Local\Temp\ipykernel_8848\2371214077.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[element] = 0.0
C:\Users\acer-pc\AppData\Local\Temp\ipykernel_8848\2371214077.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['追踪编号'] =  df['合金成分（wt.%）']

,No.,合金成分（wt.%）,Grain Size,Precipitate Distribution,Habit Plane,屈服强度,抗拉强度 (UTS),Al,Zn,Mn,...,Sr,Sm,Sc,Gd,Y,Zr,Nd,Ag,Yb,追踪编号
0,1,Mg-0.6946Y-0.0299Fe-0.0562Si,20.96,0,0,72,174,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0000,0.6946,0.0,0.0,0.0,0.0,No1-Mg-0.6946Y-0.0299Fe-0.0562Si
1,2,Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si,18.37,0,0,84,188,0.0,0.00,0.0,...,0.0,0.0,0.0,0.2714,0.7323,0.0,0.0,0.0,0.0,No2-Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si
2,3,Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si,13.22,0,0,86,188,0.0,0.00,0.0,...,0.0,0.0,0.0,0.7524,0.6239,0.0,0.0,0.0,0.0,No3-Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si
3,4,Mg-2.54Gd-0.51Zn-0.3Mn,160.00,晶界+晶内,基面,284,362,0.0,0.51,0.3,...,0.0,0.0,0.0,2.5400,0.0000,0.0,0.0,0.0,0.0,No4-Mg-2.54Gd-0.51Zn-0.3Mn
4,5,Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn,175.00,晶界+晶内,基面,316,382,0.0,0.46,0.3,...,0.0,0.0,0.0,1.7900,0.6800,0.0,0.0,0.0,0.0,No5-Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,Mg-6Al-3Sn-0.3Mn,60.00,晶界+晶内,1,116,204,6.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No865-Mg-6Al-3Sn-0.3Mn
875,876,Mg-9Al-3Sn-0.3Mn,58.00,晶界+晶内,1,140,157,9.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No866-Mg-9Al-3Sn-0.3Mn
877,878,Mg-1Al-5Sn-0.3Mn,357.00,晶界+晶内,1,85,190,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No867-Mg-1Al-5Sn-0.3Mn
878,879,Mg-1Al-5Sn-0.3Mn,60.00,晶界+晶内,1,121,180,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No868-Mg-1Al-5Sn-0.3Mn-2
879,880,Mg-1Al-5Sn-0.3Mn,56.00,晶界+晶内,1,156,184,1.0,0.00,0.3,...,0.0,0.0,0.0,0.0000,0.0000,0.0,0.0,0.0,0.0,No869-Mg-1Al-5Sn-0.3Mn-3

In [39]:
print(df.columns)
df=df[[ 'Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn',
       'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni', 'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc',
       'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb','Grain Size', 'Precipitate Distribution',
       'Habit Plane', '屈服强度', '抗拉强度 (UTS)', '追踪编号']] 
display(df)

df.to_excel('train_data_20240607original.xlsx')

Index(['No.', '合金成分（wt.%）', 'Grain Size', 'Precipitate Distribution',
       'Habit Plane', '屈服强度', '抗拉强度 (UTS)', 'Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn',
       'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni', 'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc',
       'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb', '追踪编号'],
      dtype='object')

,Al,Zn,Mn,Mg,Li,Sn,Ce,La,Ca,Si,...,Zr,Nd,Ag,Yb,Grain Size,Precipitate Distribution,Habit Plane,屈服强度,抗拉强度 (UTS),追踪编号
0,0.0,0.00,0.0,99.2193,0.0,0.0,0.0,0.0,0.0,0.0562,...,0.0,0.0,0.0,0.0,20.96,0,0,72,174,No1-Mg-0.6946Y-0.0299Fe-0.0562Si
1,0.0,0.00,0.0,98.9491,0.0,0.0,0.0,0.0,0.0,0.0316,...,0.0,0.0,0.0,0.0,18.37,0,0,84,188,No2-Mg-0.7323Y-0.2714Gd-0.0156Fe-0.0316Si
2,0.0,0.00,0.0,98.5869,0.0,0.0,0.0,0.0,0.0,0.0265,...,0.0,0.0,0.0,0.0,13.22,0,0,86,188,No3-Mg-0.6239Y-0.7524Gd-0.0103Fe-0.0265Si
3,0.0,0.51,0.3,96.6500,0.0,0.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,160.00,晶界+晶内,基面,284,362,No4-Mg-2.54Gd-0.51Zn-0.3Mn
4,0.0,0.46,0.3,96.7700,0.0,0.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,175.00,晶界+晶内,基面,316,382,No5-Mg-1.79Gd-0.68Y-0.46Zn-0.3Mn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,6.0,0.00,0.3,90.7000,0.0,3.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,60.00,晶界+晶内,1,116,204,No865-Mg-6Al-3Sn-0.3Mn
875,9.0,0.00,0.3,87.7000,0.0,3.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,58.00,晶界+晶内,1,140,157,No866-Mg-9Al-3Sn-0.3Mn
877,1.0,0.00,0.3,93.7000,0.0,5.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,357.00,晶界+晶内,1,85,190,No867-Mg-1Al-5Sn-0.3Mn
878,1.0,0.00,0.3,93.7000,0.0,5.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,60.00,晶界+晶内,1,121,180,No868-Mg-1Al-5Sn-0.3Mn-2
879,1.0,0.00,0.3,93.7000,0.0,5.0,0.0,0.0,0.0,0.0000,...,0.0,0.0,0.0,0.0,56.00,晶界+晶内,1,156,184,No869-Mg-1Al-5Sn-0.3Mn-3

In [1]:
import pandas as pd
# 对析出相和惯习面进行编码
df = pd.read_excel('train_data_20240607original.xlsx')
# df.to_excel('20240607.xlsx')

# 惯习面编码
# 定义映射字典
Habit_Panel = {
    '无': 0,
    '1': 1,
    '1+柱面': 2,
    "1+基面": 3,
    "基面": 4,
    "基面+柱面":5, # 球形颗粒也把它当做杂质
    "柱面": 6
}

Precipitation_phase_distribution = {
    '无': 0,
    '晶界': 1,
    '晶内': 2,
    '晶界+晶内': 3,
    '晶内+晶界': 3
}

# 使用replace方法对数据进行编码
df['Habit Plane'] = df['Habit Plane'].replace(Habit_Panel)
df['Precipitate Distribution'] = df['Precipitate Distribution'].replace(Precipitation_phase_distribution)

# 显示更新后的DataFrame以验证替换是否正确
print(df[['Habit Plane', 'Precipitate Distribution']])


# 计算pymatgen特征
from pymatgen.core import Composition
# print(df)
elements = ['Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn', 'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni',
            'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc', 'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb']
weightPercentage = df[elements]
# print(weightPercentage)
# 元素
# 从权重字典中提取组分信息,转换为元素序列
def to_comp(x):
    try:
        return Composition.from_weight_dict(x.to_dict())
    except Exception as ex:
        print(x, ex)

compSeries = weightPercentage.apply(to_comp, axis=1)
print(compSeries)


from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
import pandas as pd
# 创建 DataFrame
from strength_calculation import calculate_Strength
df_comp = pd.DataFrame({"composition": compSeries})
# print('hello')
# 初始化特征扩展器
featurizer = ElementProperty.from_preset("magpie")
# 应用特征扩展器
df_comp = featurizer.featurize_dataframe(df_comp, "composition")
df_comp = WenAlloys().featurize_dataframe(df_comp, "composition")
df_comp = Meredig().featurize_dataframe(df_comp, "composition")
for columnName, obj in df_comp.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_comp[columnName]
        
all = pd.concat([df_comp,df[['Grain Size', 'Precipitate Distribution',
       'Habit Plane', '屈服强度', '抗拉强度 (UTS)', '追踪编号']]],axis = 1)
all = calculate_Strength(all)

C:\Users\admin\AppData\Local\Temp\ipykernel_20744\749608683.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Precipitate Distribution'] = df['Precipitate Distribution'].replace(Precipitation_phase_distribution)

    Habit Plane  Precipitate Distribution
0             0                         0
1             0                         0
2             0                         0
3             4                         3
4             4                         3
..          ...                       ...
864           1                         3
865           1                         3
866           1                         3
867           1                         3
868           1                         3

[869 rows x 2 columns]

ModuleNotFoundError: No module named 'pymatgen'

根据公式计算屈服强度和抗拉强度

In [48]:
from strength_calculation import calculate_Strength
all = pd.read_excel('Final_train_data.xlsx')
all = calculate_Strength(all)
all.to_excel('Final_train_data.xlsx')

In [27]:
import pandas as pd

df=pd.read_excel('Final_train_data.xlsx',index_col = 0)
print(df.columns)
df = pd.concat([df[df.columns[:-8]],df[['Calculated Solid Solution', 'Calculated Grain Boundary','Calculated Yield Strength','屈服强度', '抗拉强度 (UTS)', '追踪编号']]],axis = 1)
df.to_excel('FULL_general.xlsx')

Index(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0',
       'MagpieData minimum Number', 'MagpieData maximum Number',
       'MagpieData range Number', 'MagpieData mean Number',
       'MagpieData avg_dev Number', 'MagpieData mode Number',
       'MagpieData minimum MendeleevNumber',
       ...
       'frac f valence electrons', 'Grain Size', 'Precipitate Distribution',
       'Habit Plane', 'Calculated Solid Solution', 'Calculated Grain Boundary',
       'Calculated Yield Strength', '屈服强度', '抗拉强度 (UTS)', '追踪编号'],
      dtype='object', length=287)

分别生成含有析出相和不含有析出相的数据

In [37]:
import pandas as pd

# 读取Excel文件
df = pd.read_excel('FULL_general.xlsx',index_col = 0)

# 筛选'Habit Plane'和'Precipitate Distribution'均为0的数据
no_precipitate_data = df[(df['Habit Plane'] == 0) |(df['Precipitate Distribution'] == 0)]

# 筛选其他数据
with_precipitate_data = df[(df['Habit Plane'] != 0) & (df['Precipitate Distribution'] != 0)]

# 保存数据到新的Excel文件
no_precipitate_data.to_excel('No_precipitate_data.xlsx', index=False)
with_precipitate_data.to_excel('With_precipitate_data.xlsx', index=False)

In [ ]:
# 生成预测数据集结果