生成原始数据（包含元素和形貌以及目标）

In [42]:
# import pandas as pd 
# f0924 = pd.read_excel('data/20230924.xlsx')
# f1106 = pd.read_excel('data/20231106.xlsx')
# FULL = pd.concat([f0924,f1106]).fillna(0)
# FULL = FULL[['Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn', 'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni',
#        'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc', 'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb', '晶粒尺寸', '惯习面', '析出相分布', '屈服强度',
#        '抗拉强度 （UTS）', '延伸率', '追踪编号']]
# FULL['惯习面'] = pd.Categorical(FULL['惯习面']).codes
# FULL['析出相分布'] = pd.Categorical(FULL['析出相分布']).codes
# FULL.to_excel('data/FULL_Raw.xlsx',index = False)

单独生成Wenalloy

In [29]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]  # 仅取出元素部分
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
df_new = WenAlloys().featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['屈服强度',
       '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_wenalloy.xlsx')

                 composition
0           (Al, Zn, Mn, Mg)
1           (Al, Zn, Mn, Mg)
2           (Al, Zn, Mn, Mg)
3           (Al, Zn, Mn, Mg)
4           (Al, Zn, Mn, Mg)
..                       ...
747      (Zn, Mg, Gd, Y, Yb)
748      (Zn, Mg, Gd, Y, Yb)
749  (Zn, Mg, Ca, Gd, Y, Yb)
750  (Zn, Mg, Ca, Gd, Y, Yb)
751  (Zn, Mg, Ca, Gd, Y, Yb)

[752 rows x 1 columns]

WenAlloys: 100%|██████████| 752/752 [01:12<00:00, 10.44it/s]

composition
Weight Fraction
Atomic Fraction

单独生成Elmental_fraction

In [1]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
df_new = ElementFraction().featurize_dataframe(df_new, "composition")

for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['屈服强度', '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_element_fraction.xlsx')
display(df_new)
# df = WenAlloys().featurize_dataframe(df, "composition")
# display(df)
# df = ElementFraction().featurize_dataframe(df, "composition")
# display(df)
# df = Meredig().featurize_dataframe(df, "composition")
# display(df)

C:\Users\acer-pc\anaconda3\envs\pytorch310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

                 composition
0           (Al, Zn, Mn, Mg)
1           (Al, Zn, Mn, Mg)
2           (Al, Zn, Mn, Mg)
3           (Al, Zn, Mn, Mg)
4           (Al, Zn, Mn, Mg)
..                       ...
747      (Zn, Mg, Gd, Y, Yb)
748      (Zn, Mg, Gd, Y, Yb)
749  (Zn, Mg, Ca, Gd, Y, Yb)
750  (Zn, Mg, Ca, Gd, Y, Yb)
751  (Zn, Mg, Ca, Gd, Y, Yb)

[752 rows x 1 columns]

ElementFraction: 100%|██████████| 752/752 [01:06<00:00, 11.26it/s]

composition

,H,He,Li,Be,B,C,N,O,F,Ne,...,Cf,Es,Fm,Md,No,Lr,屈服强度,抗拉强度 （UTS）,延伸率,追踪编号
0,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,165.00,250.00,12.00,20230924-1-3Al-1Zn-0.3Mn
1,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,260.00,290.00,11.00,20230924-2-3Al-1Zn-0.3Mn
2,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,207.00,289.00,33.00,20230924-3-3Al-1Zn-0.3Mn
3,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,380.00,430.00,13.20,20230924-4-3Al-1Zn-1Mn
4,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,242.00,371.00,18.70,20230924-5-3Al-1Zn-1Mn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,223.88,290.25,7.05,20231106-311-Mg-1Gd-1Y-0.2Zn-0.9Yb
748,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,213.24,280.47,8.67,20231106-312-Mg-1Gd-1Y-0.2Zn-1.2Yb
749,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,208.97,270.95,7.01,20231106-313-Mg-1Gd-1Y-0.2Zn-0.3Ca-0.6Yb
750,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,233.67,304.83,7.94,20231106-314-Mg-1Gd-1Y-0.2Zn-0.45Ca-0.45Yb
751,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,23.67,301.17,8.76,20231106-315-Mg-1Gd-1Y-0.2Zn-0.6Ca-0.3Yb

单独生成Magpie特征

In [ ]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')  # raw没有索引 
weightPercentage = df_origin.iloc[:, :-7]  # 仅取出元素部分
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
featurizer = ElementProperty.from_preset("magpie")
df_new = featurizer.featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['屈服强度',
       '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_magpie2.xlsx')

单独生成Merdig特征

In [27]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]  # 仅取出元素部分
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
df_new = Meredig().featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['屈服强度',
       '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_merdig2.xlsx')

                 composition
0           (Al, Zn, Mn, Mg)
1           (Al, Zn, Mn, Mg)
2           (Al, Zn, Mn, Mg)
3           (Al, Zn, Mn, Mg)
4           (Al, Zn, Mn, Mg)
..                       ...
747      (Zn, Mg, Gd, Y, Yb)
748      (Zn, Mg, Gd, Y, Yb)
749  (Zn, Mg, Ca, Gd, Y, Yb)
750  (Zn, Mg, Ca, Gd, Y, Yb)
751  (Zn, Mg, Ca, Gd, Y, Yb)

[752 rows x 1 columns]

Meredig: 100%|██████████| 752/752 [01:05<00:00, 11.43it/s]

composition

Magpie +　Merdig

In [37]:
df1=pd.read_excel('data/FULL_magpie2.xlsx',index_col = 0)
df2=pd.read_excel('data/FULL_merdig3.xlsx',index_col = 0)
df3=pd.read_excel('data/FULL_Raw.xlsx')
df = pd.concat([df1.iloc[:,:-4],df2.iloc[:,:-4],df3[['屈服强度',
       '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df.to_excel('data/FULL_magpie&Merdig6.xlsx')

In [43]:
df1=pd.read_excel('data/FULL_magpie2.xlsx',index_col = 0)
df2=pd.read_excel('data/FULL_Raw.xlsx')
df = pd.concat([df1.iloc[:,:-4],df2[['屈服强度',
       '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df.to_excel('data/FULL_magpie2.xlsx')

elements+morphology+empirical

In [ ]:
# df1=pd.read_excel('data/FULL_Raw.xlsx').iloc[]
# df2=pd.read_excel('data/FULL_8.xlsx',index_col = 0)

Magpie + WenAlloy+ Morphology + ElementFraction

In [15]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
featurizer = ElementProperty.from_preset("magpie")
df_new = featurizer.featurize_dataframe(df_new, "composition")
df_new = WenAlloys().featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['晶粒尺寸', '惯习面', '析出相分布', '屈服强度', '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_magpie&Morphology4.xlsx')
display(df_new)
# df = WenAlloys().featurize_dataframe(df, "composition")
# display(df)
# df = ElementFraction().featurize_dataframe(df, "composition")
# display(df)
# df = Meredig().featurize_dataframe(df, "composition")
# display(df)

                 composition
0           (Al, Zn, Mn, Mg)
1           (Al, Zn, Mn, Mg)
2           (Al, Zn, Mn, Mg)
3           (Al, Zn, Mn, Mg)
4           (Al, Zn, Mn, Mg)
..                       ...
747      (Zn, Mg, Gd, Y, Yb)
748      (Zn, Mg, Gd, Y, Yb)
749  (Zn, Mg, Ca, Gd, Y, Yb)
750  (Zn, Mg, Ca, Gd, Y, Yb)
751  (Zn, Mg, Ca, Gd, Y, Yb)

[752 rows x 1 columns]

ElementProperty: 100%|██████████| 752/752 [01:04<00:00, 11.63it/s]
WenAlloys: 100%|██████████| 752/752 [01:14<00:00, 10.15it/s]

composition
Weight Fraction
Atomic Fraction

,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,MagpieData mean MendeleevNumber,...,Mean cohesive energy,Interant electrons,Interant s electrons,Interant p electrons,Interant d electrons,Interant f electrons,Shear modulus mean,Shear modulus delta,Shear modulus local mismatch,Shear modulus strength model
0,12.0,30.0,18.0,12.112392,0.217496,12.0,52.0,73.0,21.0,68.118900,...,1.562658,6.0,0.0,1.0,5.0,0.0,17.766038,0.162505,0.395989,-0.006987
1,12.0,30.0,18.0,12.112392,0.217496,12.0,52.0,73.0,21.0,68.118900,...,1.562658,6.0,0.0,1.0,5.0,0.0,17.766038,0.162505,0.395989,-0.006987
2,12.0,30.0,18.0,12.112392,0.217496,12.0,52.0,73.0,21.0,68.118900,...,1.562658,6.0,0.0,1.0,5.0,0.0,17.766038,0.162505,0.395989,-0.006987
3,12.0,30.0,18.0,12.153703,0.296433,12.0,52.0,73.0,21.0,68.069076,...,1.567299,6.0,0.0,1.0,5.0,0.0,17.953615,0.243955,0.580340,-0.013142
4,12.0,30.0,18.0,12.153703,0.296433,12.0,52.0,73.0,21.0,68.069076,...,1.567299,6.0,0.0,1.0,5.0,0.0,17.953615,0.243955,0.580340,-0.013142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,12.0,70.0,58.0,12.246985,0.490787,12.0,12.0,69.0,57.0,67.741225,...,1.522180,9.0,0.0,0.0,2.0,7.0,17.393068,0.047278,0.059817,-0.000966
748,12.0,70.0,58.0,12.272766,0.541769,12.0,12.0,69.0,57.0,67.727976,...,1.522251,9.0,0.0,0.0,2.0,7.0,17.388653,0.048969,0.064464,-0.001079
749,12.0,70.0,58.0,12.236511,0.469300,12.0,7.0,69.0,62.0,67.640479,...,1.522738,9.0,0.0,0.0,2.0,7.0,17.378875,0.051968,0.073821,-0.001290
750,12.0,70.0,58.0,12.231285,0.458601,12.0,7.0,69.0,62.0,67.590214,...,1.523017,9.0,0.0,0.0,2.0,7.0,17.371793,0.054158,0.080792,-0.001450
751,12.0,70.0,58.0,12.226066,0.447933,12.0,7.0,69.0,62.0,67.540021,...,1.523295,9.0,0.0,0.0,2.0,7.0,17.364721,0.056259,0.087744,-0.001610

In [44]:
df_new = pd.read_excel('data/FULL_magpie2.xlsx',index_col = 0)
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
df_new = pd.concat([df_new.iloc[:,:-4],df_origin[['晶粒尺寸', '惯习面', '析出相分布','屈服强度',
        '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_magpie&Morphology4.xlsx')

5 magpie+Wenalloy

In [36]:
df_magpie = pd.read_excel('data/FULL_magpie2.xlsx',index_col = 0).iloc[:,:-4]
# display(df_magpie)
df_WenAlloy = pd.read_excel('data/FULL_wenalloy.xlsx',index_col = 0).iloc[:,:-4]
# display(df_WenAlloy)
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
# display(df_origin)
df_new = pd.concat([df_magpie,df_WenAlloy,df_origin[['屈服强度',
        '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_magpie&WenAlloys5.xlsx')

4 Magpie+ Morphology

In [ ]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
featurizer = ElementProperty.from_preset("magpie")
df_new = featurizer.featurize_dataframe(df_new, "composition")
# df_new = WenAlloys().featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['屈服强度', '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_magpie&WenAlloys5.xlsx')
display(df_new)
# df = WenAlloys().featurize_dataframe(df, "composition")
# display(df)
# df = ElementFraction().featurize_dataframe(df, "composition")
# display(df)
# df = Meredig().featurize_dataframe(df, "composition")
# display(df)

Magpie + WenAlloy+Morphology + ElementFraction

In [39]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
featurizer = ElementProperty.from_preset("magpie")
df_new = featurizer.featurize_dataframe(df_new, "composition")
# df_new = WenAlloys().featurize_dataframe(df_new, "composition")

df_new = WenAlloys().featurize_dataframe(df_new, "composition")
df_new = ElementFraction().featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
df_new = pd.concat([df_new,df_origin[['晶粒尺寸', '惯习面', '析出相分布','屈服强度', '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)

# df = WenAlloys().featurize_dataframe(df, "composition")
# display(df)
# df = ElementFraction().featurize_dataframe(df, "composition")
# display(df)
# df = Meredig().featurize_dataframe(df, "composition")
# display(df)

df_new.to_excel('data/FULL_Magpie&Wen&Mor&Fraction7.xlsx')
display(df_new)

                 composition
0           (Al, Zn, Mn, Mg)
1           (Al, Zn, Mn, Mg)
2           (Al, Zn, Mn, Mg)
3           (Al, Zn, Mn, Mg)
4           (Al, Zn, Mn, Mg)
..                       ...
747      (Zn, Mg, Gd, Y, Yb)
748      (Zn, Mg, Gd, Y, Yb)
749  (Zn, Mg, Ca, Gd, Y, Yb)
750  (Zn, Mg, Ca, Gd, Y, Yb)
751  (Zn, Mg, Ca, Gd, Y, Yb)

[752 rows x 1 columns]

ElementProperty: 100%|██████████| 752/752 [01:05<00:00, 11.56it/s]
WenAlloys: 100%|██████████| 752/752 [01:12<00:00, 10.41it/s]
ElementFraction: 100%|██████████| 752/752 [00:55<00:00, 13.61it/s]

composition
Weight Fraction
Atomic Fraction
惯习面
析出相分布
追踪编号

,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,MagpieData mean MendeleevNumber,...,Cf,Es,Fm,Md,No,Lr,晶粒尺寸,屈服强度,抗拉强度 （UTS）,延伸率
0,12.0,30.0,18.0,12.112392,0.217496,12.0,52.0,73.0,21.0,68.118900,...,0,0,0,0,0,0,40.00,165.00,250.00,12.00
1,12.0,30.0,18.0,12.112392,0.217496,12.0,52.0,73.0,21.0,68.118900,...,0,0,0,0,0,0,1.60,260.00,290.00,11.00
2,12.0,30.0,18.0,12.112392,0.217496,12.0,52.0,73.0,21.0,68.118900,...,0,0,0,0,0,0,1.60,207.00,289.00,33.00
3,12.0,30.0,18.0,12.153703,0.296433,12.0,52.0,73.0,21.0,68.069076,...,0,0,0,0,0,0,0.65,380.00,430.00,13.20
4,12.0,30.0,18.0,12.153703,0.296433,12.0,52.0,73.0,21.0,68.069076,...,0,0,0,0,0,0,3.00,242.00,371.00,18.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,12.0,70.0,58.0,12.246985,0.490787,12.0,12.0,69.0,57.0,67.741225,...,0,0,0,0,0,0,4.50,223.88,290.25,7.05
748,12.0,70.0,58.0,12.272766,0.541769,12.0,12.0,69.0,57.0,67.727976,...,0,0,0,0,0,0,4.20,213.24,280.47,8.67
749,12.0,70.0,58.0,12.236511,0.469300,12.0,7.0,69.0,62.0,67.640479,...,0,0,0,0,0,0,4.83,208.97,270.95,7.01
750,12.0,70.0,58.0,12.231285,0.458601,12.0,7.0,69.0,62.0,67.590214,...,0,0,0,0,0,0,3.92,233.67,304.83,7.94
751,12.0,70.0,58.0,12.226066,0.447933,12.0,7.0,69.0,62.0,67.540021,...,0,0,0,0,0,0,3.81,23.67,301.17,8.76

In [40]:
df_new=pd.read_excel('data/FULL_Magpie&Wen&Mor&Fraction7.xlsx',index_col = 0)

df_origin = pd.read_excel('data/FULL_Raw.xlsx')
df_new = pd.concat([df_new.iloc[:,:-4],df_origin[['晶粒尺寸', '惯习面', '析出相分布','屈服强度',
        '抗拉强度 （UTS）', '延伸率', '追踪编号']]],axis = 1)
df_new.to_excel('data/FULL_Magpie&Wen&Mor&Fraction7.xlsx')

In [ ]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
featurizer = ElementProperty.from_preset("magpie")
df_new = featurizer.featurize_dataframe(df_new, "composition")
df_new = WenAlloys().featurize_dataframe(df_new, "composition")
for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]

# df = WenAlloys().featurize_dataframe(df, "composition")
# display(df)
# df = ElementFraction().featurize_dataframe(df, "composition")
# display(df)
# df = Meredig().featurize_dataframe(df, "composition")
# display(df)

import math
elements = ['Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn', 'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni',
'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc', 'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb',]
Bi_Table = {
    'Ag': 92.2,
    'Al': 120,
    'Bi': 100,  # 估计
    'Ca': 402.56,
    'Ce': 2077,
    'Cu': 100,  # 估计
    'Fe': 429.72,
    'Gd': 900,
    'La': 1698,
    'Li': 159.1,
    'Mg': 0,  # 规定为0
    'Mn': 158,
    'Nd': 813,
    'Ni': 524.93,
    'Sc': 477,
    'Si': 408.94,
    'Sm': 480.94,
    'Sn': 280,
    'Sr': 670.19,
    'Ti': 100,  # 没有记录！ V错误
    'Y': 800,
    'Yb': 432.87,
    'Zn': 40,
    'Zr': 273
}
qh_Table = {
    'Ag': 1000,  # 估计
    'Al': 2000,
    'Bi': 1000,  # 估计
    'Ca': 1000,  # 估计
    'Ce': 50827,
    'Cu': 1000,  # 估计
    'Fe': 1000,  # 估计
    'Gd': 5000,
    'La': 3322,
    'Li': 1000,  # 估计
    'Mg': 0,  # 应该是210，但是这里不算
    'Mn': 2000,
    'Nd': 20390,
    'Ni': 1000,  # 估计
    'Sc': 1570,
    'Si': 18000,
    'Sm': 1000,  # 估计
    'Sn': 3000,
    'Sr': 1000,  # 估计
    'Ti': 1000,  # 没有记录！ V错误
    'Y': 1000,
    'Yb': 1000,  # 估计
    'Zn': 18000,
    'Zr': 2038
}
# from pprint import pprint
# pprint(dict(zip(elements, Bi_Table)))


def calculate_solubility_strength(row):
    strength = 0
    for element in elements:
        # 对每个元素应用公式：Bi系数**1.5 * 比例
        strength += ((Bi_Table[element] ** 1.5) * row.get(f"{element} fraction", 0))
    return strength



def calculate_jingjie(row):
    if row["晶粒尺寸"] == 0:
        return 0
    strength = 210
    for element in elements:
        strength += (qh_Table[element] * row.get(f"{element} fraction", 0))
    return strength / math.sqrt(row["晶粒尺寸"])

df_new["计算固溶"] =df_new[[f"{i} fraction" for i in elements]].apply(calculate_solubility_strength, axis=1)
df_new["计算晶界"] = df_new[[f"{i} fraction" for i in elements] + ["晶粒尺寸"]].apply(calculate_jingjie, axis=1)
df_new["计算总强度"] = df_new["计算固溶"] + df_new["计算晶界"]

df_new.to_excel('data/FULL_magpie&WenAlloys3.xlsx')
display(df_new)

In [ ]:
import pandas as pd
from matminer.featurizers.composition.composite import ElementProperty
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition.element import ElementFraction
from matminer.featurizers.composition.composite import Meredig
from pymatgen.core import Composition

import pandas as pd
df_origin = pd.read_excel('data/FULL_Raw.xlsx')
weightPercentage = df_origin.iloc[:, :-7]
compSeries = weightPercentage.apply(lambda x: Composition.from_weight_dict(x.to_dict()), axis=1)
# print(compSeries[1])
df_new = pd.DataFrame({"composition": compSeries})
display(df_new)
featurizer = ElementProperty.from_preset("magpie")
df_new = featurizer.featurize_dataframe(df_new, "composition")
df_new = Meredig().featurize_dataframe(df_new, "composition")

for columnName, obj in df_new.dtypes.items():
    if obj == "object":
        print(columnName)
        del df_new[columnName]
import math
elements = ['Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn', 'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni',
'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc', 'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb',]
Bi_Table = {
    'Ag': 92.2,
    'Al': 120,
    'Bi': 100,  # 估计
    'Ca': 402.56,
    'Ce': 2077,
    'Cu': 100,  # 估计
    'Fe': 429.72,
    'Gd': 900,
    'La': 1698,
    'Li': 159.1,
    'Mg': 0,  # 规定为0
    'Mn': 158,
    'Nd': 813,
    'Ni': 524.93,
    'Sc': 477,
    'Si': 408.94,
    'Sm': 480.94,
    'Sn': 280,
    'Sr': 670.19,
    'Ti': 100,  # 没有记录！ V错误
    'Y': 800,
    'Yb': 432.87,
    'Zn': 40,
    'Zr': 273
}
qh_Table = {
    'Ag': 1000,  # 估计
    'Al': 2000,
    'Bi': 1000,  # 估计
    'Ca': 1000,  # 估计
    'Ce': 50827,
    'Cu': 1000,  # 估计
    'Fe': 1000,  # 估计
    'Gd': 5000,
    'La': 3322,
    'Li': 1000,  # 估计
    'Mg': 0,  # 应该是210，但是这里不算
    'Mn': 2000,
    'Nd': 20390,
    'Ni': 1000,  # 估计
    'Sc': 1570,
    'Si': 18000,
    'Sm': 1000,  # 估计
    'Sn': 3000,
    'Sr': 1000,  # 估计
    'Ti': 1000,  # 没有记录！ V错误
    'Y': 1000,
    'Yb': 1000,  # 估计
    'Zn': 18000,
    'Zr': 2038
}
# from pprint import pprint
# pprint(dict(zip(elements, Bi_Table)))


def calculate_solubility_strength(row):
    strength = 0
    for element in elements:
        # 对每个元素应用公式：Bi系数**1.5 * 比例
        strength += ((Bi_Table[element] ** 1.5) * row.get(f"{element} fraction", 0))
    return strength



def calculate_jingjie(row):
    if row["晶粒尺寸"] == 0:
        return 0
    strength = 210
    for element in elements:
        strength += (qh_Table[element] * row.get(f"{element} fraction", 0))
    return strength / math.sqrt(row["晶粒尺寸"])

df_new["计算固溶"] =df_new[[f"{i} fraction" for i in elements]].apply(calculate_solubility_strength, axis=1)
df_new["计算晶界"] = df_new[[f"{i} fraction" for i in elements] + ["晶粒尺寸"]].apply(calculate_jingjie, axis=1)
df_new["计算总强度"] = df_new["计算固溶"] + df_new["计算晶界"]
df_new = pd.concat([df_new,df_origin.iloc[:,-4:]],axis=1)
df_new.to_excel('data/FULL_elements&mor&formula.xlsx')

In [26]:
df_origin=pd.read_excel('data/FULL_magpie&Morphology4.xlsx')
df_new=df_origin.iloc[:,:-4]
import math
elements = ['Al', 'Zn', 'Mn', 'Mg', 'Li', 'Sn', 'Ce', 'La', 'Ca', 'Si', 'Cu', 'Ni',
'Fe', 'Bi', 'Ti', 'Sr', 'Sm', 'Sc', 'Gd', 'Y', 'Zr', 'Nd', 'Ag', 'Yb',]
Bi_Table = {
    'Ag': 92.2,
    'Al': 120,
    'Bi': 100,  # 估计
    'Ca': 402.56,
    'Ce': 2077,
    'Cu': 100,  # 估计
    'Fe': 429.72,
    'Gd': 900,
    'La': 1698,
    'Li': 159.1,
    'Mg': 0,  # 规定为0
    'Mn': 158,
    'Nd': 813,
    'Ni': 524.93,
    'Sc': 477,
    'Si': 408.94,
    'Sm': 480.94,
    'Sn': 280,
    'Sr': 670.19,
    'Ti': 100,  # 没有记录！ V错误
    'Y': 800,
    'Yb': 432.87,
    'Zn': 40,
    'Zr': 273
}
qh_Table = {
    'Ag': 1000,  # 估计
    'Al': 2000,
    'Bi': 1000,  # 估计
    'Ca': 1000,  # 估计
    'Ce': 50827,
    'Cu': 1000,  # 估计
    'Fe': 1000,  # 估计
    'Gd': 5000,
    'La': 3322,
    'Li': 1000,  # 估计
    'Mg': 0,  # 应该是210，但是这里不算
    'Mn': 2000,
    'Nd': 20390,
    'Ni': 1000,  # 估计
    'Sc': 1570,
    'Si': 18000,
    'Sm': 1000,  # 估计
    'Sn': 3000,
    'Sr': 1000,  # 估计
    'Ti': 1000,  # 没有记录！ V错误
    'Y': 1000,
    'Yb': 1000,  # 估计
    'Zn': 18000,
    'Zr': 2038
}
# from pprint import pprint
# pprint(dict(zip(elements, Bi_Table)))


def calculate_solubility_strength(row):
    strength = 0
    for element in elements:
        # 对每个元素应用公式：Bi系数**1.5 * 比例
        strength += ((Bi_Table[element] ** 1.5) * row.get(f"{element} fraction", 0))
    return strength



def calculate_jingjie(row):
    if row["晶粒尺寸"] == 0:
        return 0
    strength = 210
    for element in elements:
        strength += (qh_Table[element] * row.get(f"{element} fraction", 0))
    return strength / math.sqrt(row["晶粒尺寸"])

df_new["计算固溶"] =df_new[[f"{i} fraction" for i in elements]].apply(calculate_solubility_strength, axis=1)
df_new["计算晶界"] = df_new[[f"{i} fraction" for i in elements] + ["晶粒尺寸"]].apply(calculate_jingjie, axis=1)
df_new["计算总强度"] = df_new["计算固溶"] + df_new["计算晶界"]
df_new = pd.concat([df_new,df_origin.iloc[:,-4:]],axis=1)
df_new.to_excel('data/FULL_magpie&morphology&empirical_formula6')

KeyError: "None of [Index(['Al fraction', 'Zn fraction', 'Mn fraction', 'Mg fraction',\n       'Li fraction', 'Sn fraction', 'Ce fraction', 'La fraction',\n       'Ca fraction', 'Si fraction', 'Cu fraction', 'Ni fraction',\n       'Fe fraction', 'Bi fraction', 'Ti fraction', 'Sr fraction',\n       'Sm fraction', 'Sc fraction', 'Gd fraction', 'Y fraction',\n       'Zr fraction', 'Nd fraction', 'Ag fraction', 'Yb fraction'],\n      dtype='object')] are in the [columns]"